CREATE TABLE ACCOUNT(
    ID VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID)
);

CREATE TABLE CHARACTERS(
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CHARACTER_LEVEL NUMERIC NOT NULL,
    CURRENT_EXPERIENCE NUMERIC NOT NULL,
    NEXT_EXPERIENCE NUMERIC NOT NULL,
    GOLD NUMERIC NOT NULL,
    CONSTRAINT CHARACTERS_PK PRIMARY KEY (ID)
);

CREATE TABLE ACCOUNT_CHARACTERS(
    ACCOUNT_ID VARCHAR(255) NOT NULL,
    CHARACTER_ID VARCHAR(255) NOT NULL,
    CONSTRAINT ACCOUNT_CHARACTERS_ACCOUNT_ID_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
    CONSTRAINT ACCOUNT_CHARACTERS_CHARACTER_ID_FK FOREIGN KEY (CHARACTER_ID) REFERENCES CHARACTERS(ID)
);

CREATE TABLE ACTION_POINTS(
    CHARACTERS_ID VARCHAR(255) NOT NULL,
    CURRENT_HEALTH_POINTS NUMERIC NOT NULL,
    MAX_HEALTH_POINTS NUMERIC NOT NULL,
    CURRENT_MAGIC_POINTS NUMERIC NOT NULL,
    MAX_MAGIC_POINTS NUMERIC NOT NULL,
    CONSTRAINT ACTION_POINTS_CHARACTERS_FK FOREIGN KEY (CHARACTERS_ID) REFERENCES CHARACTERS(ID)
);

CREATE TABLE ATTRIBUTES(
    CHARACTERS_ID VARCHAR(255) NOT NULL,
    STRENGTH NUMERIC NOT NULL,
    AGILITY NUMERIC NOT NULL,
    INTELLIGENCE NUMERIC NOT NULL,
    CONSTRAINT ATTRIBUTES_CHARACTERS_FK FOREIGN KEY (CHARACTERS_ID) REFERENCES CHARACTERS(ID)
);
