CREATE TABLE ACCOUNT(
    ID VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID)
);

CREATE TABLE ROLES(
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT ROLES_PK PRIMARY KEY (ID)
);

CREATE TABLE ACCOUNT_ROLES(
    ACCOUNT_ID VARCHAR(255) NOT NULL,
    ROLES_ID VARCHAR(255) NOT NULL,
    CONSTRAINT ACCOUNT_ROLES_ACCOUNT_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
    CONSTRAINT ACCOUNT_ROLES_ROLES_FK FOREIGN KEY (ROLES_ID) REFERENCES ROLES(ID)
);

CREATE TABLE HEROES(
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    BACKGROUND VARCHAR(255) NOT NULL,
    HERO_LEVEL NUMERIC NOT NULL,
    CURRENT_EXPERIENCE NUMERIC NOT NULL,
    NEXT_EXPERIENCE NUMERIC NOT NULL,
    CURRENT_HEALTH_POINTS NUMERIC NOT NULL,
    MAX_HEALTH_POINTS NUMERIC NOT NULL,
    CURRENT_MAGIC_POINTS NUMERIC NOT NULL,
    MAX_MAGIC_POINTS NUMERIC NOT NULL,
    STRENGTH NUMERIC NOT NULL,
    CONSTITUTION NUMERIC NOT NULL,
    DEXTERITY NUMERIC NOT NULL,
    INTELLIGENCE NUMERIC NOT NULL,
    WISDOM NUMERIC NOT NULL,
    CHARISMA NUMERIC NOT NULL,
    GOLD NUMERIC NOT NULL,
    HERO_CLASS VARCHAR(255) NOT NULL,
    ACCOUNT_ID VARCHAR(255) NOT NULL,
    CONSTRAINT CHARACTERS_PK PRIMARY KEY (ID),
    CONSTRAINT CHARACTERS_ACCOUNT_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);