CREATE TABLE ACCOUNT(
    ID VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID)
);